# Generated by Django 3.2.1 on 2021-05-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='emails',
            new_name='email',
        ),
    ]
